### ISSUE TITLE
no prop type

### ISSUE THREAD

**Issue by goldylucks** [DavidWells/react-proptype-autocomplete#12]
I have a component `AuthModal` that has a prop `modalStatus` of type `string`, and the "string" part isn't showing on autocomplete (see screenshot below)

I'm using flow:

```jsx
// AuthModal.jsx
type Props = {
  modalStatus: string,
  onModalOverlayClick: Function,
  onGoToLoginClick: Function,
  onGoToSignupClick: Function,
  onGoToForgotPasswordClick: Function,
  onLogin: Function,
  onSignup: Function,
  onCloseModal: Function,
  onLostPassword: Function,
  onGoToYearlyPaymentClick: Function,
  onGoToLifetimePaymentClick: Function,
  onTogglePaymentModeClick: Function,
};
```

versions:
```bash
$ apm -v
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

let me know if there's anything else I should post here

![image](https://cloud.githubusercontent.com/assets/6963212/25031192/bc4e1218-20fd-11e7-8c7c-5c24e06f4af2.png)

**Comment by niiapa** [comment]
Tried setting language to Babel?

**Comment by goldylucks** [comment]
don't remember what this is about TBH
